// =============================================================
// RETTSKILDESØK PRO – KILDEBASE OG SØKEMOTORER
// Alle URL-er er verifisert og oppdatert per 2026
// =============================================================

const SEARCH_ENGINES = [
  {
    id: 'google',
    label: '🔍 Google',
    baseUrl: 'https://www.google.com/search?q=',
    supportsDateFilter: true,
    supportsSiteFilter: true,
    supportsFiletype: true,
    dateFormat: 'google', // after:YYYY-01-01 before:YYYY-12-31
  },
  {
    id: 'bing',
    label: '🔎 Bing',
    baseUrl: 'https://www.bing.com/search?q=',
    supportsDateFilter: false,
    supportsSiteFilter: true,
    supportsFiletype: true,
  },
  {
    id: 'duckduckgo',
    label: '🦆 DuckDuckGo',
    baseUrl: 'https://duckduckgo.com/?q=',
    supportsDateFilter: false,
    supportsSiteFilter: true,
    supportsFiletype: false,
  },
  {
    id: 'scholar',
    label: '🎓 Google Scholar',
    baseUrl: 'https://scholar.google.com/scholar?q=',
    supportsDateFilter: true,
    supportsSiteFilter: true,
    supportsFiletype: false,
    dateFormat: 'scholar', // as_ylo=YYYY&as_yhi=YYYY appended separately
  },
  {
    id: 'base',
    label: '🌐 BASE (Bielefeld)',
    baseUrl: 'https://www.base-search.net/Search/Results?type=all&look=all&q=',
    supportsDateFilter: false,
    supportsSiteFilter: true,
    supportsFiletype: false,
    sitePrefix: 'url:', // BASE uses url: not site:
  },
  {
    id: 'lovdata',
    label: '⚖️ Lovdata Direkte',
    baseUrl: 'https://lovdata.no/search#query=',
    supportsDateFilter: false,
    supportsSiteFilter: false,
    supportsFiletype: false,
    direct: true,
    note: 'Søker direkte i Lovdata (krever ev. abonnement for fulltekst)',
  },
  {
    id: 'rettsdata',
    label: '📚 Rettsdata Direkte',
    baseUrl: 'https://www.rettsdata.no/search?q=',
    supportsDateFilter: false,
    supportsSiteFilter: false,
    supportsFiletype: false,
    direct: true,
    note: 'Gyldendals rettslige databas – krever abonnement',
  },
];

// =============================================================
// ALLE RETTSKILDER KATEGORISERT
// Farger: lov=#1d4ed8, forarbeid=#06b6d4, domstol=#a855f7, praksis=#64748b, internasjonal=#059669
// =============================================================

const SOURCE_CATEGORIES = [
  {
    id: 'cat_lovsamlinger',
    title: '1. Lover & Lovsamlinger',
    colorClass: 'weight-lov',
    sources: [
      {
        id: 'ld_lover',
        label: 'Lovdata: Gjeldende lover',
        desc: 'Alle formelle, konsoliderte lover i kraft',
        value: 'lovdata.no/dokument/NL',
        defaultChecked: true,
        keywords: ['lovdata', 'lover', 'lovverk', 'lov om', 'paragraf', '§'],
      },
      {
        id: 'ld_forskrifter',
        label: 'Lovdata: Forskrifter',
        desc: 'Sentrale (SF) og lokale (LF) forskrifter',
        value: 'lovdata.no/dokument/SF|lovdata.no/dokument/LF',
        defaultChecked: true,
        keywords: ['forskrift', 'sf-', 'lf-'],
      },
      {
        id: 'ld_kunngjoring',
        label: 'Lovdata: Kunngjøringer',
        desc: 'Nye lover og forskrifter nylig kunngjort i Norsk Lovtidend',
        value: 'lovdata.no/dokument/LTI|lovdata.no/dokument/LTII',
        defaultChecked: false,
        keywords: ['kunngjøring', 'lovtidend'],
      },
      {
        id: 'norgeslover',
        label: 'Norgeslover.no (UiO)',
        desc: 'UiOs åpne lovportal med annoterte lover',
        value: 'norgeslover.no',
        defaultChecked: true,
        keywords: ['norgeslover', 'uio', 'det juridiske fakultet'],
      },
      {
        id: 'lovdata_historisk',
        label: 'Lovdata: Historiske versjoner',
        desc: 'Tidligere lovversjoner og opphevede lover',
        value: 'lovdata.no/dokument/HIST',
        defaultChecked: false,
        keywords: ['historisk', 'opphevet', 'tidligere versjon'],
      },
    ],
  },
  {
    id: 'cat_forarbeider',
    title: '2. Forarbeider & Stortingsdokumenter',
    colorClass: 'weight-forarbeid',
    sources: [
      {
        id: 'reg_nou',
        label: 'Regjeringen: NOU',
        desc: 'Norges offentlige utredninger fra utvalgene',
        value: 'regjeringen.no/no/dokumenter/nou',
        defaultChecked: true,
        keywords: ['nou', 'norges offentlige utredning', 'utvalg', 'kommisjon'],
      },
      {
        id: 'reg_prop',
        label: 'Regjeringen: Prop. & Meld.',
        desc: 'Lovproposisjoner (Prop. L) og stortingsmeldinger (Meld. St.)',
        value: 'regjeringen.no/no/dokumenter/prop|regjeringen.no/no/dokumenter/meld',
        defaultChecked: true,
        keywords: ['proposisjon', 'prop.', 'meld. st.', 'stortingsmelding', 'lovproposisjon'],
      },
      {
        id: 'reg_otprp',
        label: 'Regjeringen: Ot.prp. (historisk)',
        desc: 'Eldre odelstingsproposisjoner (før 2009)',
        value: 'regjeringen.no/no/dokumenter/otprp',
        defaultChecked: false,
        keywords: ['odelstingsproposisjon', 'ot.prp'],
      },
      {
        id: 'reg_tolkning',
        label: 'Justisdep. Lovavdeling',
        desc: 'Tolkningsuttalelser fra Justis- og beredskapsdepartementet',
        value: 'regjeringen.no/no/dokumenter/tolkningsuttalelser',
        defaultChecked: true,
        keywords: ['tolkningsuttalelse', 'lovavdelingen', 'justisdepartementet', 'juridisk vurdering'],
      },
      {
        id: 'stortinget_dok',
        label: 'Stortinget: Innst. & Saker',
        desc: 'Komitéinnstillinger, representantforslag og vedtak',
        value: 'stortinget.no/no/Saker-og-publikasjoner',
        defaultChecked: true,
        keywords: ['stortinget', 'innstilling', 'representantforslag', 'komité'],
      },
      {
        id: 'stortinget_forhandlinger',
        label: 'Stortinget: Forhandlinger',
        desc: 'Stortingstidende – alle debatter i fulltekst',
        value: 'stortinget.no/no/Saker-og-publikasjoner/Stortingstidende',
        defaultChecked: false,
        keywords: ['stortingstidende', 'debatt', 'votering'],
      },
      {
        id: 'dfo_kudos',
        label: 'KUDOS (DFO)',
        desc: 'Statsforvaltningens evalueringer, rapporter og utredninger',
        value: 'kudos.dfo.no',
        defaultChecked: false,
        keywords: ['kudos', 'dfo', 'direktorat for forvaltning', 'statsforvaltning'],
      },
    ],
  },
  {
    id: 'cat_domstoler',
    title: '3. Domstolsinstanser',
    colorClass: 'weight-domstol',
    sources: [
      {
        id: 'ld_hr',
        label: 'Lovdata: Høyesterett',
        desc: 'Høyesterettsdommer og kjennelser i fulltekst (HR)',
        value: 'lovdata.no/dokument/HR|lovdata.no/dokument/HRS',
        defaultChecked: true,
        keywords: ['høyesterett', 'hr-', 'rt-', 'prejudikat'],
      },
      {
        id: 'ld_lagmannsrett',
        label: 'Lovdata: Lagmannsrettene',
        desc: 'Dommer fra alle seks lagmannsretter (LG, LA, LB, LF, LE, LH)',
        value: 'lovdata.no/dokument/LG|lovdata.no/dokument/LA|lovdata.no/dokument/LB|lovdata.no/dokument/LE|lovdata.no/dokument/LF|lovdata.no/dokument/LH',
        defaultChecked: false,
        keywords: ['lagmannsrett', 'ankedomstol'],
      },
      {
        id: 'ld_tingrett',
        label: 'Lovdata: Tingrettene',
        desc: 'Dommer fra tingrettene (TRS)',
        value: 'lovdata.no/dokument/TRS',
        defaultChecked: false,
        keywords: ['tingrett', 'byrett', 'herredsrett'],
      },
      {
        id: 'hoyesterett_web',
        label: 'Høyesterett.no (direktelenke)',
        desc: 'Nye avgjørelser publisert direkte fra Høyesterett',
        value: 'www.domstol.no/no/hoyesterett/avgjorelser',
        defaultChecked: true,
        keywords: ['hoyesterett.no', 'domstol.no'],
      },
      {
        id: 'rettspraksis_no',
        label: 'Rettspraksis.no',
        desc: 'Historisk, dugnadsdrevet domsarkiv med eldre rettsavgjørelser',
        value: 'rettspraksis.no',
        defaultChecked: false,
        keywords: ['rettspraksis', 'historisk dom', 'eldre dom'],
      },
      {
        id: 'ld_arbeidsretten',
        label: 'Lovdata: Arbeidsretten',
        desc: 'Spesialdomstol for tariff- og arbeidstvister (ARD)',
        value: 'lovdata.no/dokument/ARD',
        defaultChecked: false,
        keywords: ['arbeidsretten', 'ard', 'tariffavtale', 'arbeidstvist'],
      },
      {
        id: 'ld_trygderetten',
        label: 'Lovdata: Trygderetten',
        desc: 'Ankeinstans for trygde- og pensjonssaker (TRR)',
        value: 'lovdata.no/dokument/TRR',
        defaultChecked: false,
        keywords: ['trygderetten', 'trr', 'trygd', 'pensjon anke'],
      },
    ],
  },
  {
    id: 'cat_nemnder',
    title: '4. Nemnder & Tilsynsorganer',
    colorClass: 'weight-praksis',
    sources: [
      {
        id: 'sivilombudet',
        label: 'Sivilombudet',
        desc: 'Uttalelser i forvaltningssaker – kontrollerer forvaltningens vedtak',
        value: 'sivilombudet.no/uttalelser',
        defaultChecked: true,
        keywords: ['sivilombudet', 'ombudsmann', 'forvaltningskontroll'],
      },
      {
        id: 'kofa',
        label: 'KOFA',
        desc: 'Klagenemnda for offentlige anskaffelser – vedtak og rådgivende uttalelser',
        value: 'kofa.no/praksis',
        defaultChecked: false,
        keywords: ['kofa', 'anskaffelse', 'anbud', 'innkjøp', 'offentlig kontrakt'],
      },
      {
        id: 'skatteetaten',
        label: 'Skatteetaten',
        desc: 'Skatte-ABC, bindende forhåndsuttalelser og retningslinjer',
        value: 'skatteetaten.no/rettskilder|skatteetaten.no/skatte-abc',
        defaultChecked: false,
        keywords: ['skatt', 'mva', 'avgift', 'ligning', 'skatte-abc', 'bfu'],
      },
      {
        id: 'skatteklagenemnda',
        label: 'Skatteklagenemnda',
        desc: 'Vedtak fra skatteklagenemnda (tidl. Riksskattenemnda)',
        value: 'skatteklagenemnda.no',
        defaultChecked: false,
        keywords: ['skatteklage', 'skatteklagenemnda', 'riksskattenemnda'],
      },
      {
        id: 'arbeidstilsynet',
        label: 'Arbeidstilsynet',
        desc: 'AML-kommentarer, veiledere og HMS-regelverk',
        value: 'arbeidstilsynet.no',
        defaultChecked: false,
        keywords: ['arbeidsmiljø', 'aml', 'hms', 'verneombud', 'arbeidstilsyn'],
      },
      {
        id: 'nav_rettskilde',
        label: 'NAV Rettskilde',
        desc: 'Rundskriv og instrukser til folketrygdloven og NAV-loven',
        value: 'lovdata.no/nav',
        defaultChecked: false,
        keywords: ['nav', 'folketrygd', 'trygderett', 'stønad', 'arbeidsavklaringspenger'],
      },
      {
        id: 'une',
        label: 'UNE (Utlendingsnemnda)',
        desc: 'Praksisnotat og vedtak i utlendingssaker',
        value: 'une.no/praksis',
        defaultChecked: false,
        keywords: ['une', 'utlendingsnemnda', 'asyl', 'visum', 'utvisning', 'statsborgerskap'],
      },
      {
        id: 'diskrimineringsnemnda',
        label: 'Diskrimineringsnemnda',
        desc: 'Avgjørelser innen likestilling og diskriminering',
        value: 'diskrimineringsnemnda.no/avgjørelser',
        defaultChecked: false,
        keywords: ['diskriminering', 'likestilling', 'trakassering', 'ldo'],
      },
      {
        id: 'datatilsynet',
        label: 'Datatilsynet',
        desc: 'GDPR-vedtak, sanksjonssaker og retningslinjer',
        value: 'datatilsynet.no/regelverk-og-verktoy',
        defaultChecked: false,
        keywords: ['gdpr', 'personvern', 'personopplysning', 'datatilsynet', 'personvernforordningen'],
      },
      {
        id: 'finanstilsynet',
        label: 'Finanstilsynet',
        desc: 'Rundskriv, tilsynsrapporter og konsesjonsvedtak',
        value: 'finanstilsynet.no/nyheter-og-publikasjoner',
        defaultChecked: false,
        keywords: ['finanstilsyn', 'bank', 'forsikring', 'finans', 'revisjon', 'konsesjon'],
      },
      {
        id: 'konkurransetilsynet',
        label: 'Konkurransetilsynet',
        desc: 'Vedtak om fusjoner, kartell og markedsadgang',
        value: 'konkurransetilsynet.no/vedtak-og-uttalelser',
        defaultChecked: false,
        keywords: ['konkurranse', 'fusjon', 'oppkjøp', 'kartell', 'konkurranseloven'],
      },
      {
        id: 'nkom',
        label: 'Nasjonal kommunikasjonsmyndighet (Nkom)',
        desc: 'Vedtak innen elektronisk kommunikasjon og post',
        value: 'nkom.no/vedtak',
        defaultChecked: false,
        keywords: ['nkom', 'elektronisk kommunikasjon', 'ekomloven', 'post', 'telenor'],
      },
      {
        id: 'nve',
        label: 'NVE (Norges vassdrags- og energidirektorat)',
        desc: 'Vedtak og konsesjoner innen energi og vassdragsrett',
        value: 'nve.no/juridiske-dokumenter',
        defaultChecked: false,
        keywords: ['nve', 'vassdrag', 'energi', 'konsesjon', 'regulering', 'strøm'],
      },
      {
        id: 'ptk_nemnd',
        label: 'Pakkereisenemnda',
        desc: 'Klagesaker i reise- og forbrukerrett',
        value: 'pakkereisenemnda.no/vedtak',
        defaultChecked: false,
        keywords: ['pakkereise', 'reiseklage', 'forbruker reise'],
      },
      {
        id: 'forbrukertilsynet',
        label: 'Forbrukertilsynet',
        desc: 'Vedtak og retningslinjer innen forbrukerrett og markedsføring',
        value: 'forbrukertilsynet.no/vedtak-og-uttalelser',
        defaultChecked: false,
        keywords: ['forbrukertilsyn', 'markedsføringsloven', 'forbruker', 'mfl'],
      },
      {
        id: 'forbrukerklageutvalget',
        label: 'Forbrukerklageutvalget',
        desc: 'Vedtak i forbrukerkjøps- og håndverkersaker',
        value: 'forbrukerklageutvalget.no/vedtak',
        defaultChecked: false,
        keywords: ['forbrukerkjøp', 'håndverker', 'reklamasjon', 'mangel'],
      },
    ],
  },
  {
    id: 'cat_akademisk',
    title: '5. Akademisk & Juridisk Litteratur',
    colorClass: 'weight-forarbeid',
    sources: [
      {
        id: 'idunn',
        label: 'Idunn.no',
        desc: 'Norsk faglig tidsskriftdatabase – inkl. Lov og Rett, TfE, m.fl.',
        value: 'idunn.no',
        defaultChecked: false,
        keywords: ['idunn', 'lov og rett', 'tidsskrift', 'juridisk artikkel', 'jussens venner'],
      },
      {
        id: 'uio_jus',
        label: 'UiO Juridisk Fakultet',
        desc: 'Arbeidskopier, PhD-avhandlinger og faglige fremstillinger',
        value: 'uio.no/studier/emner/jus|folk.uio.no',
        defaultChecked: false,
        keywords: ['uio', 'juridisk fakultet', 'avhandling'],
      },
      {
        id: 'uib_jus',
        label: 'UiB Juridisk Fakultet',
        desc: 'Forskning og publikasjoner fra det juridiske miljøet i Bergen',
        value: 'uib.no/jus|bora.uib.no',
        defaultChecked: false,
        keywords: ['uib', 'bergen', 'juridisk'],
      },
      {
        id: 'cristin',
        label: 'Cristin (NVI-registeret)',
        desc: 'Nasjonalt register for vitenskapelig publisering i Norge',
        value: 'app.cristin.no',
        defaultChecked: false,
        keywords: ['cristin', 'nvi', 'vitenskapelig', 'forskning'],
      },
    ],
  },
  {
    id: 'cat_eu_eos',
    title: '6. EU / EØS-rett',
    colorClass: 'weight-lov',
    sources: [
      {
        id: 'eurlex',
        label: 'EUR-Lex',
        desc: 'EUs offisielle rettsportal – forordninger, direktiver og domspraksis',
        value: 'eur-lex.europa.eu',
        defaultChecked: false,
        keywords: ['eu', 'eøs', 'direktiv', 'forordning', 'celex', 'traktat'],
      },
      {
        id: 'curia',
        label: 'Curia (EU-domstolen)',
        desc: 'Dommer og uttalelser fra EU-domstolen og Retten',
        value: 'curia.europa.eu',
        defaultChecked: false,
        keywords: ['eu-domstolen', 'curia', 'generaladvokat', 'prejudisiell'],
      },
      {
        id: 'efta_court',
        label: 'EFTA-domstolen',
        desc: 'Rådgivende uttalelser og dommer om EØS-avtalens innhold',
        value: 'eftacourt.int/cases',
        defaultChecked: false,
        keywords: ['efta', 'eøs-avtalen', 'eea court', 'rådgivende uttalelse'],
      },
      {
        id: 'esa',
        label: 'ESA (EFTA Surveillance Authority)',
        desc: 'EFTAs overvåkningsorgan – statsstøtte og markedsrett',
        value: 'esa.int/cases',
        defaultChecked: false,
        keywords: ['esa', 'efta surveillance', 'statsstøtte', 'konkurranseregler eøs'],
      },
      {
        id: 'europarl',
        label: 'Europaparlamentet',
        desc: 'Europaparlamentsvedtak og komitearbeid',
        value: 'europarl.europa.eu',
        defaultChecked: false,
        keywords: ['europaparlament', 'eu parlament', 'parlamentsvedtak'],
      },
    ],
  },
  {
    id: 'cat_emr',
    title: '7. Menneskerettigheter',
    colorClass: 'weight-domstol',
    sources: [
      {
        id: 'hudoc',
        label: 'HUDOC (EMD – Strasbourg)',
        desc: 'Alle dommer og avvisningsavgjørelser fra EMD',
        value: 'hudoc.echr.coe.int',
        defaultChecked: false,
        keywords: ['emd', 'emk', 'menneskerettigheter', 'strasbourg', 'hudoc', 'echr'],
      },
      {
        id: 'coe',
        label: 'Europarådet',
        desc: 'Konvensjoner, traktater og anbefalinger fra Europarådet',
        value: 'coe.int/en/web/conventions',
        defaultChecked: false,
        keywords: ['europarådet', 'council of europe', 'konvensjon', 'emk artikkel'],
      },
      {
        id: 'un_treaty',
        label: 'UN Treaty Collection',
        desc: 'FNs traktatregister – internasjonale konvensjoner og protokoller',
        value: 'treaties.un.org',
        defaultChecked: false,
        keywords: ['fn', 'un', 'internasjonale konvensjoner', 'traktat', 'icj'],
      },
      {
        id: 'ohchr',
        label: 'OHCHR (FN Menneskerettigheter)',
        desc: 'FNs høykommissær for menneskerettigheter – komitéuttalelser og veiledning',
        value: 'ohchr.org',
        defaultChecked: false,
        keywords: ['ohchr', 'fn menneskerettigheter', 'komitéuttalelse', 'sp', 'øsk'],
      },
    ],
  },
  {
    id: 'cat_internasjonal',
    title: '8. Internasjonal & Komparativ Rett',
    colorClass: 'weight-domstol',
    sources: [
      {
        id: 'icj',
        label: 'ICJ (Den internasjonale domstol)',
        desc: 'FNs øverste domstol – mellomstatlige tvister og rådgivende uttalelser',
        value: 'icj-cij.org/cases',
        defaultChecked: false,
        keywords: ['icj', 'internasjonal domstol', 'haag', 'mellomstatlig'],
      },
      {
        id: 'itlos',
        label: 'ITLOS (Havrettsdomstolen)',
        desc: 'Internasjonalt tribunal for havrett i Hamburg',
        value: 'itlos.org/cases',
        defaultChecked: false,
        keywords: ['itlos', 'havrett', 'unclos', 'kontinentalsokkel'],
      },
      {
        id: 'wto_dispute',
        label: 'WTO Tvisteløsning',
        desc: 'WTOs tvisteløsningspanel og ankeorgan',
        value: 'wto.org/english/tratop_e/dispu_e',
        defaultChecked: false,
        keywords: ['wto', 'gatt', 'handelsrett', 'tvisteløsning', 'panel'],
      },
      {
        id: 'uncitral',
        label: 'UNCITRAL (FN Handelsrett)',
        desc: 'FNs kommisjon for internasjonal handelsrett – modelllover og voldgift',
        value: 'uncitral.org',
        defaultChecked: false,
        keywords: ['uncitral', 'voldgift', 'internasjonal handel', 'modelloven'],
      },
      {
        id: 'retsinformation',
        label: 'Retsinformation.dk (Danmark)',
        desc: 'Dansk lovportal – nyttig for komparativ nordisk rett',
        value: 'retsinformation.dk',
        defaultChecked: false,
        keywords: ['dansk', 'nordisk', 'retsinformation', 'komparativ'],
      },
      {
        id: 'riksdagen_se',
        label: 'Riksdagen.se (Sverige)',
        desc: 'Svensk lovportal – nyttig for komparativ nordisk rett',
        value: 'riksdagen.se/sv/dokument-och-lagar/lagar',
        defaultChecked: false,
        keywords: ['svensk', 'riksdagen', 'nordisk', 'komparativ'],
      },
    ],
  },
  {
    id: 'cat_fagmyndigheter',
    title: '9. Fagdepartement & Direktorater',
    colorClass: 'weight-praksis',
    sources: [
      {
        id: 'regjeringen_alle',
        label: 'Regjeringen.no (generelt)',
        desc: 'Alle departementers publikasjoner, veiledere og brev',
        value: 'regjeringen.no',
        defaultChecked: false,
        keywords: ['departement', 'statsråd', 'rundskriv regjeringen'],
      },
      {
        id: 'kdd',
        label: 'Kommunal- og distriktsdep.',
        desc: 'Plan- og bygningsrett, kommunerett, valglovgivning',
        value: 'regjeringen.no/no/dep/kdd',
        defaultChecked: false,
        keywords: ['kommunerett', 'plan og bygg', 'pbl', 'boligrett', 'valglov'],
      },
      {
        id: 'statsforvalter',
        label: 'Statsforvalteren',
        desc: 'Statlige tilsyns- og klageinstanser i fylkene',
        value: 'statsforvalteren.no',
        defaultChecked: false,
        keywords: ['statsforvalter', 'fylkesmann', 'klage', 'tilsyn'],
      },
      {
        id: 'lovdata_rundskriv',
        label: 'Lovdata: Rundskriv',
        desc: 'Departementale og direktoratets rundskriv tilgjengelig via Lovdata',
        value: 'lovdata.no/dokument/RUNDSKRIV',
        defaultChecked: false,
        keywords: ['rundskriv', 'instruks', 'tolkningsbrev'],
      },
    ],
  },
];

// =============================================================
// FAGOMRÅDE-BUNDLES
// =============================================================

const BUNDLES = [
  {
    id: 'all',
    label: '✓ Alle',
    sourceIds: null, // null = velg alt
  },
  {
    id: 'arbeidsrett',
    label: '👷 Arbeidsrett',
    sourceIds: [
      'ld_lover', 'ld_forskrifter', 'norgeslover',
      'reg_nou', 'reg_prop', 'reg_tolkning',
      'ld_hr', 'ld_arbeidsretten',
      'hoyesterett_web', 'arbeidstilsynet', 'diskrimineringsnemnda',
    ],
  },
  {
    id: 'forretningsjus',
    label: '🏢 Forretningsjus & Skatt',
    sourceIds: [
      'ld_lover', 'ld_forskrifter', 'norgeslover',
      'reg_nou', 'reg_prop',
      'ld_hr', 'hoyesterett_web',
      'skatteetaten', 'skatteklagenemnda', 'finanstilsynet', 'konkurransetilsynet',
      'eurlex', 'efta_court',
    ],
  },
  {
    id: 'forvaltning',
    label: '🏛️ Forvaltningsrett',
    sourceIds: [
      'ld_lover', 'ld_forskrifter', 'norgeslover',
      'reg_nou', 'reg_prop', 'reg_tolkning',
      'stortinget_dok', 'dfo_kudos', 'lovdata_rundskriv',
      'ld_hr', 'sivilombudet', 'datatilsynet',
      'statsforvalter', 'regjeringen_alle',
    ],
  },
  {
    id: 'strafferett',
    label: '⚖️ Strafferett',
    sourceIds: [
      'ld_lover', 'ld_forskrifter', 'norgeslover',
      'reg_nou', 'reg_prop',
      'ld_hr', 'ld_lagmannsrett', 'ld_tingrett', 'hoyesterett_web',
    ],
  },
  {
    id: 'familierett',
    label: '👨‍👩‍👧 Familie & Arv',
    sourceIds: [
      'ld_lover', 'ld_forskrifter', 'norgeslover',
      'reg_nou', 'reg_prop',
      'ld_hr', 'ld_lagmannsrett',
    ],
  },
  {
    id: 'menneskerett',
    label: '🌍 Menneskerettigheter',
    sourceIds: [
      'ld_lover', 'norgeslover',
      'ld_hr', 'hoyesterett_web',
      'hudoc', 'coe', 'un_treaty', 'ohchr',
      'efta_court', 'eurlex',
    ],
  },
  {
    id: 'domstoler',
    label: '🏛️ Kun Domstoler',
    sourceIds: [
      'ld_hr', 'ld_lagmannsrett', 'ld_tingrett',
      'hoyesterett_web', 'rettspraksis_no',
      'ld_arbeidsretten', 'ld_trygderetten',
      'efta_court', 'hudoc',
    ],
  },
];

// =============================================================
// JURIDISK TESAURUS / SYNONYMUTVIDELSE
// =============================================================

const JURIDISK_TESAURUS = {
  mislighold: ['kontraktsbrudd', 'avvik', 'kontraktsmislighold', 'vesentlig mislighold'],
  oppsigelse: ['avskjed', 'sluttavtale', 'arbeidsforholdets opphør', 'endringsoppsigelse'],
  erstatning: ['skadeserstatning', 'oppreisning', 'ansvar', 'culpaansvar', 'objektivt ansvar'],
  mangel: ['feil', 'kjøpsmangel', 'leveringsavvik', 'rettslig mangel'],
  ekspropriasjon: ['tvangserverv', 'rådighetsinnskrenkning', 'avståelse'],
  straff: ['sanksjoner', 'fengselsstraff', 'bøtestraff', 'forvaring'],
  personvern: ['GDPR', 'personopplysninger', 'behandlingsgrunnlag', 'samtykke'],
  diskriminering: ['trakassering', 'likestilling', 'usaklig forskjellsbehandling'],
  voldgift: ['mekling', 'alternativ tvisteløsning', 'ADR', 'skilsrett'],
  fusjon: ['sammenslåing', 'virksomhetsoverdragelse', 'oppkjøp', 'aksjeoverdragelse'],
};

// Eksporter til global scope (kompatibelt med enkel HTML/JS)
window.SEARCH_ENGINES = SEARCH_ENGINES;
window.SOURCE_CATEGORIES = SOURCE_CATEGORIES;
window.BUNDLES = BUNDLES;
window.JURIDISK_TESAURUS = JURIDISK_TESAURUS;
