// =============================================================
// RETTSKILDESØK PRO v3.0 – KILDEBASE OG SØKEMOTORER
// Alle URL-er verifisert. Direkte portal-URL-er der tilgjengelig.
// =============================================================

const APP_VERSION = '3.0.0';

// =============================================================
// SØKEMOTORER
// directSearch: true = åpner portalen direkte (ingen site:-filter)
// portalSearchUrl: URL-mal for direkte portalsøk, {q} = søkeord
// =============================================================
const SEARCH_ENGINES = [
  {
    id: 'google',
    label: '🔍 Google',
    baseUrl: 'https://www.google.com/search?q=',
    supportsDateFilter: true,
    supportsSiteFilter: true,
    supportsFiletype: true,
    dateFormat: 'google',
    note: 'Støtter site:, filetype:, after:/before:. Beste allround-valg for rettskilde-søk.',
  },
  {
    id: 'bing',
    label: '🔎 Bing',
    baseUrl: 'https://www.bing.com/search?q=',
    supportsDateFilter: false,
    supportsSiteFilter: true,
    supportsFiletype: true,
    note: 'Støtter site: og filetype:. Kan gi andre treff enn Google på norske sider.',
  },
  {
    id: 'duckduckgo',
    label: '🦆 DuckDuckGo',
    baseUrl: 'https://duckduckgo.com/?q=',
    supportsDateFilter: false,
    supportsSiteFilter: true,
    supportsFiletype: false,
    note: 'Ingen sporingsdata lagres. Støtter site:-filter, men ikke filtype.',
  },
  {
    id: 'scholar',
    label: '🎓 Google Scholar',
    baseUrl: 'https://scholar.google.com/scholar?q=',
    supportsDateFilter: true,
    supportsSiteFilter: true,
    dateFormat: 'scholar',
    note: 'Ideelt for juridisk teori, artikler, avhandlinger og kommentarutgaver.',
  },
  {
    id: 'base',
    label: '🌐 BASE (Bielefeld)',
    baseUrl: 'https://www.base-search.net/Search/Results?type=all&look=all&q=',
    supportsDateFilter: false,
    supportsSiteFilter: true,
    supportsFiletype: false,
    sitePrefix: 'url:',
    note: 'Europeisk akademisk åpen-tilgang-base. Bruker url: i stedet for site:.',
  },
  {
    id: 'multitab',
    label: '🗂️ Multisøk (én fane per kilde)',
    baseUrl: null,
    supportsDateFilter: false,
    supportsSiteFilter: false,
    supportsFiletype: false,
    isMultiTab: true,
    note: 'Åpner én nettleserfane per valgt kilde med skreddersydd søke-URL. Gir best dekning.',
  },
];

// =============================================================
// DIREKTE PORTAL-URL-MALER
// {q} erstattes med søkeordet (URL-encodet)
// Brukes av multisøk og direkte portal-lenker
// =============================================================
const PORTAL_SEARCH_URLS = {
  // Lovdata
  'lovdata.no/dokument/NL':        'https://lovdata.no/search#query={q}&facet%5Btype%5D=LOV',
  'lovdata.no/dokument/SF':        'https://lovdata.no/search#query={q}&facet%5Btype%5D=FOR',
  'lovdata.no/dokument/LF':        'https://lovdata.no/search#query={q}&facet%5Btype%5D=FOR',
  'lovdata.no/dokument/HR':        'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/HRS':       'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/LG':        'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/LA':        'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/LB':        'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/LE':        'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/LF2':       'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/LH':        'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/TRS':       'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/ARD':       'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/TRR':       'https://lovdata.no/search#query={q}&facet%5Btype%5D=RDOMSTOL',
  'lovdata.no/dokument/HIST':      'https://lovdata.no/search#query={q}',
  'lovdata.no/dokument/LTI':       'https://lovdata.no/search#query={q}&facet%5Btype%5D=LTI',
  'lovdata.no/dokument/LTII':      'https://lovdata.no/search#query={q}&facet%5Btype%5D=LTII',
  'lovdata.no/dokument/RUNDSKRIV': 'https://lovdata.no/search#query={q}&facet%5Btype%5D=RUNDSKRIV',
  'lovdata.no/nav':                'https://lovdata.no/search#query={q}&facet%5Bfagomrade%5D=nav',
  // Regjeringen
  'regjeringen.no/no/dokumenter/nou':        'https://www.regjeringen.no/no/dokumenter/nou/?q={q}&dokumenttype=nou',
  'regjeringen.no/no/dokumenter/prop':       'https://www.regjeringen.no/no/dokumenter/proposisjoner/?q={q}',
  'regjeringen.no/no/dokumenter/meld':       'https://www.regjeringen.no/no/dokumenter/meldinger/?q={q}',
  'regjeringen.no/no/dokumenter/otprp':      'https://www.regjeringen.no/no/dokumenter/otprp/?q={q}',
  'regjeringen.no/no/dokumenter/tolkningsuttalelser': 'https://www.regjeringen.no/no/dokument/lover_regler/tolkningsuttalelser/?q={q}',
  'regjeringen.no/no/dep/kdd':               'https://www.regjeringen.no/no/sok/?q={q}&dep=kdd',
  'regjeringen.no':                          'https://www.regjeringen.no/no/sok/?q={q}',
  // Stortinget
  'stortinget.no/no/Saker-og-publikasjoner':            'https://www.stortinget.no/no/Hva-skjer-pa-Stortinget/Nyheter/?q={q}',
  'stortinget.no/no/Saker-og-publikasjoner/Stortingstidende': 'https://www.stortinget.no/no/Saker-og-publikasjoner/Stortingstidende/?q={q}',
  // Domstoler
  'www.domstol.no/no/hoyesterett/avgjorelser': 'https://www.domstol.no/no/hoyesterett/avgjorelser/?q={q}',
  'rettspraksis.no':                           'https://rettspraksis.no/?s={q}',
  // Nemnder og tilsyn
  'sivilombudet.no/uttalelser':            'https://www.sivilombudet.no/uttalelser/?search={q}',
  'kofa.no/praksis':                       'https://www.kofa.no/praksis/?q={q}',
  'skatteetaten.no/rettskilder':           'https://www.skatteetaten.no/rettskilder/?q={q}',
  'skatteetaten.no/skatte-abc':            'https://www.skatteetaten.no/rettskilder/skatte-abc/?q={q}',
  'skatteklagenemnda.no':                  'https://skatteklagenemnda.no/vedtak/?q={q}',
  'arbeidstilsynet.no':                    'https://www.arbeidstilsynet.no/om-oss/sok/?q={q}',
  'une.no/praksis':                        'https://une.no/praksis/?q={q}',
  'diskrimineringsnemnda.no/avgjørelser':  'https://www.diskrimineringsnemnda.no/avgjorelser/?q={q}',
  'datatilsynet.no/regelverk-og-verktoy':  'https://www.datatilsynet.no/regelverk-og-verktoy/finn-riktig-regelverk/?q={q}',
  'finanstilsynet.no/nyheter-og-publikasjoner': 'https://www.finanstilsynet.no/nyheter-og-publikasjoner/?q={q}',
  'konkurransetilsynet.no/vedtak-og-uttalelser': 'https://www.konkurransetilsynet.no/vedtak-og-uttalelser/?q={q}',
  'forbrukertilsynet.no/vedtak-og-uttalelser':   'https://www.forbrukertilsynet.no/vedtak-og-uttalelser/?q={q}',
  'statsforvalteren.no':                   'https://www.statsforvalteren.no/portal/Sok/?q={q}',
  'kudos.dfo.no':                          'https://kudos.dfo.no/dokument?q={q}',
  // Akademisk
  'idunn.no':       'https://www.idunn.no/search?q={q}&subject=juss',
  'app.cristin.no': 'https://app.cristin.no/search/?t=all&q={q}',
  // EU/EØS
  'eur-lex.europa.eu':  'https://eur-lex.europa.eu/search.html?text={q}&scope=EURLEX&type=quick&lang=no',
  'curia.europa.eu':    'https://curia.europa.eu/juris/recherche.jsf?language=no&query={q}',
  'eftacourt.int/cases':'https://www.eftacourt.int/cases/search/?q={q}',
  'esa.int/cases':      'https://www.esa.int/cases/?q={q}',
  // Menneskerettigheter
  'hudoc.echr.coe.int': 'https://hudoc.echr.coe.int/eng?query={q}',
  'coe.int/en/web/conventions': 'https://www.coe.int/en/web/portal/search?q={q}',
  'treaties.un.org':    'https://treaties.un.org/Pages/UNTSOnline.aspx?id=1&query={q}',
  'ohchr.org':          'https://www.ohchr.org/en/search?search_api_fulltext={q}',
  // Internasjonalt
  'icj-cij.org/cases':  'https://www.icj-cij.org/cases?q={q}',
  'wto.org/english/tratop_e/dispu_e': 'https://www.wto.org/english/tratop_e/dispu_e/dispu_status_e.htm?q={q}',
  // Nordisk
  'retsinformation.dk': 'https://www.retsinformation.dk/api/search?query={q}',
  'riksdagen.se/sv/dokument-och-lagar/lagar': 'https://www.riksdagen.se/sv/dokument-och-lagar/lagar/sokresultat/?q={q}',
  // Nye norske
  'juridika.no':              'https://juridika.no/sokesider/resultater?query={q}',
  'riksrevisjonen.no':        'https://www.riksrevisjonen.no/sok/?q={q}',
  'patentstyret.no':          'https://www.patentstyret.no/sok/?q={q}',
  'domstol.no/statistikk':    'https://www.domstol.no/no/domstol-statistikk/?q={q}',
  'snl.no/jus':               'https://snl.no/s%C3%B8k?query={q}&flt%5Bcategory%5D=jus',
  'norgeslover.no':           'https://lovdata.no/search#query={q}',
  'nkom.no/vedtak':           'https://www.nkom.no/aktuelt/vedtak/?q={q}',
  'nve.no/juridiske-dokumenter': 'https://www.nve.no/sok/?q={q}',
};

// =============================================================
// LOVNAVN FOR AUTOCOMPLETE
// =============================================================
const LOVNAVN_AUTOCOMPLETE = [
  { navn: 'Arbeidsmiljøloven (aml)', lov: 'Lov-2005-06-17-62' },
  { navn: 'Avtaleloven (avl)', lov: 'Lov-1918-05-31-4' },
  { navn: 'Aksjeloven (asl)', lov: 'Lov-1997-06-13-44' },
  { navn: 'Allmennaksjeloven (asal)', lov: 'Lov-1997-06-13-45' },
  { navn: 'Arveloven', lov: 'Lov-2019-06-14-21' },
  { navn: 'Buofl (bustadoppføringslova)', lov: 'Lov-1997-06-13-43' },
  { navn: 'Diskrimineringsloven om etnisitet', lov: 'Lov-2017-06-16-50' },
  { navn: 'Ekteskapsloven', lov: 'Lov-1991-07-04-47' },
  { navn: 'Forvaltningsloven (fvl)', lov: 'Lov-1967-02-10' },
  { navn: 'Grl. (Grunnloven)', lov: 'Lov-1814-05-17' },
  { navn: 'Husleieloven (hlL)', lov: 'Lov-1999-03-26-17' },
  { navn: 'Kjøpsloven', lov: 'Lov-1988-05-13-27' },
  { navn: 'Kommuneloven', lov: 'Lov-2018-06-22-83' },
  { navn: 'Konkursloven', lov: 'Lov-1984-06-08-58' },
  { navn: 'Likestillings- og diskrimineringsloven', lov: 'Lov-2017-06-16-51' },
  { navn: 'Menneskerettsloven (mrl)', lov: 'Lov-1999-05-21-30' },
  { navn: 'Merverdiavgiftsloven (mval)', lov: 'Lov-2009-06-19-58' },
  { navn: 'Offentleglova (offl)', lov: 'Lov-2006-05-19-16' },
  { navn: 'Pasient- og brukerrettighetsloven', lov: 'Lov-1999-07-02-63' },
  { navn: 'Personopplysningsloven', lov: 'Lov-2018-06-15-38' },
  { navn: 'Plan- og bygningsloven (pbl)', lov: 'Lov-2008-06-27-71' },
  { navn: 'Politiloven', lov: 'Lov-1995-08-04-53' },
  { navn: 'Produktansvarsloven', lov: 'Lov-1988-12-23-104' },
  { navn: 'Skatteloven (sktl)', lov: 'Lov-1999-03-26-14' },
  { navn: 'Skadeserstatningsloven (skl)', lov: 'Lov-1969-06-13-26' },
  { navn: 'Sosialtjenesteloven', lov: 'Lov-2009-12-18-131' },
  { navn: 'Straffeloven (strl)', lov: 'Lov-2005-05-20-28' },
  { navn: 'Straffeprosessloven (strpl)', lov: 'Lov-1981-05-22-25' },
  { navn: 'Tvisteloven (tvl)', lov: 'Lov-2005-06-17-90' },
  { navn: 'Vergemålsloven', lov: 'Lov-2010-03-26-9' },
  { navn: 'Årsregnskapsloven (rskl)', lov: 'Lov-1998-07-17-56' },
  { navn: 'Åndsverkloven', lov: 'Lov-2018-06-15-40' },
  { navn: 'Barnevernloven', lov: 'Lov-2021-06-18-97' },
  { navn: 'Barnelova', lov: 'Lov-1981-04-08-7' },
  { navn: 'Fjellova', lov: 'Lov-1975-06-06-31' },
  { navn: 'Havressurslova', lov: 'Lov-2008-06-06-37' },
  { navn: 'Luftfartsloven', lov: 'Lov-1993-06-11-101' },
  { navn: 'Markedsføringsloven (mfl)', lov: 'Lov-2009-01-09-2' },
  { navn: 'Forbrukerkjøpsloven (fkjl)', lov: 'Lov-2002-06-21-34' },
  { navn: 'Helsepersonelloven (hpl)', lov: 'Lov-1999-07-02-64' },
  { navn: 'NAV-loven', lov: 'Lov-2006-06-16-20' },
  { navn: 'Folketrygdloven (ftrl)', lov: 'Lov-1997-02-28-19' },
  { navn: 'Vegtrafikkloven', lov: 'Lov-1965-06-18-4' },
  { navn: 'Tomtefesteloven', lov: 'Lov-1996-12-20-106' },
  { navn: 'Oreigningslova (ekspropriasjon)', lov: 'Lov-1959-10-23-3' },
];

// =============================================================
// ALLE RETTSKILDER KATEGORISERT
// weight: rettskildemessig vekt (1=høyest, 4=lavest)
// directPortal: true = bruker PORTAL_SEARCH_URLS ved multisøk
// warning: vises som advarsel/info-notat i UI
// =============================================================
const SOURCE_CATEGORIES = [
  {
    id: 'cat_lovsamlinger',
    title: '1. Lover & Lovsamlinger',
    colorClass: 'weight-lov',
    weight: 1,
    sources: [
      {
        id: 'ld_lover',
        label: 'Lovdata: Gjeldende lover',
        desc: 'Alle formelle, konsoliderte lover i kraft',
        value: 'lovdata.no/dokument/NL',
        defaultChecked: true,
        directPortal: true,
        keywords: ['lovdata', 'lover', 'lovverk', 'lov om', 'paragraf', '§', 'nl'],
      },
      {
        id: 'ld_forskrifter',
        label: 'Lovdata: Forskrifter',
        desc: 'Sentrale (SF) og lokale (LF) forskrifter',
        value: 'lovdata.no/dokument/SF',
        defaultChecked: true,
        directPortal: true,
        keywords: ['forskrift', 'sf-', 'lf-'],
      },
      {
        id: 'ld_kunngjoring',
        label: 'Lovdata: Kunngjøringer (LTI/LTII)',
        desc: 'Nye lover og forskrifter nylig kunngjort i Norsk Lovtidend',
        value: 'lovdata.no/dokument/LTI',
        defaultChecked: false,
        directPortal: true,
        keywords: ['kunngjøring', 'lovtidend'],
      },
      {
        id: 'norgeslover',
        label: 'Norgeslover.no (UiO)',
        desc: 'UiOs åpne lovportal med annoterte lover og kommentarer',
        value: 'norgeslover.no',
        defaultChecked: true,
        directPortal: true,
        keywords: ['norgeslover', 'uio', 'det juridiske fakultet', 'lovkommentar'],
      },
      {
        id: 'lovdata_historisk',
        label: 'Lovdata: Historiske versjoner',
        desc: 'Tidligere lovversjoner og opphevede lover',
        value: 'lovdata.no/dokument/HIST',
        defaultChecked: false,
        directPortal: true,
        keywords: ['historisk', 'opphevet', 'tidligere versjon', 'eldre lov'],
      },
      {
        id: 'snl_jus',
        label: 'Store norske leksikon – Jus',
        desc: 'Juridiske begrepsforklaringer og oversiktsartikler',
        value: 'snl.no/jus',
        defaultChecked: false,
        directPortal: true,
        keywords: ['snl', 'leksikon', 'begrep', 'definisjon', 'oversikt'],
      },
    ],
  },
  {
    id: 'cat_forarbeider',
    title: '2. Forarbeider & Stortingsdokumenter',
    colorClass: 'weight-forarbeid',
    weight: 2,
    sources: [
      {
        id: 'reg_nou',
        label: 'Regjeringen: NOU',
        desc: 'Norges offentlige utredninger fra utvalgene',
        value: 'regjeringen.no/no/dokumenter/nou',
        defaultChecked: true,
        directPortal: true,
        keywords: ['nou', 'norges offentlige utredning', 'utvalg', 'kommisjon'],
      },
      {
        id: 'reg_prop',
        label: 'Regjeringen: Prop. & Meld.',
        desc: 'Lovproposisjoner (Prop. L) og stortingsmeldinger (Meld. St.)',
        value: 'regjeringen.no/no/dokumenter/prop',
        defaultChecked: true,
        directPortal: true,
        keywords: ['proposisjon', 'prop.', 'meld. st.', 'stortingsmelding', 'lovproposisjon'],
      },
      {
        id: 'reg_otprp',
        label: 'Regjeringen: Ot.prp. (historisk)',
        desc: 'Eldre odelstingsproposisjoner (før 2009)',
        value: 'regjeringen.no/no/dokumenter/otprp',
        defaultChecked: false,
        directPortal: true,
        keywords: ['odelstingsproposisjon', 'ot.prp', 'lovforarbeider eldre'],
      },
      {
        id: 'reg_tolkning',
        label: 'Justisdep. Lovavdeling – tolkningsuttalelser',
        desc: 'Tolkningsuttalelser fra Justis- og beredskapsdepartementet',
        value: 'regjeringen.no/no/dokumenter/tolkningsuttalelser',
        defaultChecked: true,
        directPortal: true,
        keywords: ['tolkningsuttalelse', 'lovavdelingen', 'justisdepartementet', 'juridisk vurdering'],
      },
      {
        id: 'stortinget_dok',
        label: 'Stortinget: Innst. & Saker',
        desc: 'Komitéinnstillinger, representantforslag og vedtak',
        value: 'stortinget.no/no/Saker-og-publikasjoner',
        defaultChecked: true,
        directPortal: true,
        keywords: ['stortinget', 'innstilling', 'representantforslag', 'komité', 'vedtak'],
      },
      {
        id: 'stortinget_forhandlinger',
        label: 'Stortinget: Forhandlinger (Stortingstidende)',
        desc: 'Alle stortingsdebatter i fulltekst',
        value: 'stortinget.no/no/Saker-og-publikasjoner/Stortingstidende',
        defaultChecked: false,
        directPortal: true,
        keywords: ['stortingstidende', 'debatt', 'votering', 'talerliste'],
      },
      {
        id: 'dfo_kudos',
        label: 'KUDOS (DFO)',
        desc: 'Statsforvaltningens evalueringer, rapporter og utredninger',
        value: 'kudos.dfo.no',
        defaultChecked: false,
        directPortal: true,
        keywords: ['kudos', 'dfo', 'direktorat for forvaltning', 'statsforvaltning', 'evaluering'],
      },
      {
        id: 'riksrevisjonen',
        label: 'Riksrevisjonen',
        desc: 'Forvaltningsrevisjoner, selskapskontroll og statsregnskap',
        value: 'riksrevisjonen.no',
        defaultChecked: false,
        directPortal: true,
        keywords: ['riksrevisjon', 'forvaltningsrevisjon', 'selskapskontroll', 'statsregnskap', 'kritikk forvaltning'],
        warning: 'Riksrevisjonsrapporter er sterke rettskilder i forvaltningsrett og offentlig rett.',
      },
    ],
  },
  {
    id: 'cat_domstoler',
    title: '3. Domstolsinstanser',
    colorClass: 'weight-domstol',
    weight: 1,
    sources: [
      {
        id: 'ld_hr',
        label: 'Lovdata: Høyesterett (HR/HRS)',
        desc: 'Høyesterettsdommer og kjennelser i fulltekst',
        value: 'lovdata.no/dokument/HR',
        defaultChecked: true,
        directPortal: true,
        keywords: ['høyesterett', 'hr-', 'rt-', 'prejudikat', 'ankeutvalg'],
      },
      {
        id: 'ld_lagmannsrett',
        label: 'Lovdata: Lagmannsrettene (LG/LA/LB/LE/LF/LH)',
        desc: 'Dommer fra alle seks lagmannsretter',
        value: 'lovdata.no/dokument/LG',
        defaultChecked: false,
        directPortal: true,
        keywords: ['lagmannsrett', 'ankedomstol', 'lg', 'la', 'lb', 'le', 'lh'],
      },
      {
        id: 'ld_tingrett',
        label: 'Lovdata: Tingrettene (TRS)',
        desc: 'Dommer fra tingrettene (begrenset utvalg på Lovdata)',
        value: 'lovdata.no/dokument/TRS',
        defaultChecked: false,
        directPortal: true,
        keywords: ['tingrett', 'byrett', 'herredsrett', 'trs'],
        warning: 'Lovdata inneholder bare et utvalg tingrettsdommer. Mange er ikke tilgjengelige gratis.',
      },
      {
        id: 'hoyesterett_web',
        label: 'Høyesterett.no – nye avgjørelser',
        desc: 'Avgjørelser publisert direkte på domstol.no (siste måneder)',
        value: 'www.domstol.no/no/hoyesterett/avgjorelser',
        defaultChecked: true,
        directPortal: true,
        keywords: ['hoyesterett.no', 'domstol.no', 'ferske dommer', 'nye avgjørelser'],
        warning: 'Viser kun avgjørelser fra de siste 3 månedene. For eldre: bruk Lovdata.',
      },
      {
        id: 'rettspraksis_no',
        label: 'Rettspraksis.no',
        desc: 'Historisk, dugnadsdrevet domsarkiv med eldre rettsavgjørelser',
        value: 'rettspraksis.no',
        defaultChecked: false,
        directPortal: true,
        keywords: ['rettspraksis', 'historisk dom', 'eldre dom', 'uoffisiell'],
        warning: 'Uoffisielt arkiv – alltid bekreft mot Lovdata for juridisk bruk.',
      },
      {
        id: 'ld_arbeidsretten',
        label: 'Lovdata: Arbeidsretten (ARD)',
        desc: 'Spesialdomstol for tariff- og arbeidstvister',
        value: 'lovdata.no/dokument/ARD',
        defaultChecked: false,
        directPortal: true,
        keywords: ['arbeidsretten', 'ard', 'tariffavtale', 'arbeidstvist', 'kollektiv arbeidsrett'],
      },
      {
        id: 'ld_trygderetten',
        label: 'Lovdata: Trygderetten (TRR)',
        desc: 'Ankeinstans for trygde- og pensjonssaker',
        value: 'lovdata.no/dokument/TRR',
        defaultChecked: false,
        directPortal: true,
        keywords: ['trygderetten', 'trr', 'trygd', 'pensjon anke', 'uføretrygd'],
      },
    ],
  },
  {
    id: 'cat_nemnder',
    title: '4. Nemnder & Tilsynsorganer',
    colorClass: 'weight-praksis',
    weight: 3,
    sources: [
      {
        id: 'sivilombudet',
        label: 'Sivilombudet',
        desc: 'Uttalelser i forvaltningssaker – kontrollerer forvaltningens vedtak',
        value: 'sivilombudet.no/uttalelser',
        defaultChecked: true,
        directPortal: true,
        keywords: ['sivilombudet', 'ombudsmann', 'forvaltningskontroll', 'klage forvaltning'],
      },
      {
        id: 'kofa',
        label: 'KOFA',
        desc: 'Klagenemnda for offentlige anskaffelser',
        value: 'kofa.no/praksis',
        defaultChecked: false,
        directPortal: true,
        keywords: ['kofa', 'anskaffelse', 'anbud', 'innkjøp', 'offentlig kontrakt', 'foa'],
      },
      {
        id: 'skatteetaten',
        label: 'Skatteetaten – Rettskilder & Skatte-ABC',
        desc: 'Skatte-ABC, bindende forhåndsuttalelser (BFU) og retningslinjer',
        value: 'skatteetaten.no/rettskilder',
        defaultChecked: false,
        directPortal: true,
        keywords: ['skatt', 'mva', 'avgift', 'ligning', 'skatte-abc', 'bfu', 'bindende forhåndsuttalelse'],
      },
      {
        id: 'skatteklagenemnda',
        label: 'Skatteklagenemnda',
        desc: 'Vedtak fra Skatteklagenemnda (tidl. Riksskattenemnda)',
        value: 'skatteklagenemnda.no',
        defaultChecked: false,
        directPortal: true,
        keywords: ['skatteklage', 'skatteklagenemnda', 'riksskattenemnda'],
      },
      {
        id: 'arbeidstilsynet',
        label: 'Arbeidstilsynet',
        desc: 'AML-kommentarer, veiledere og HMS-regelverk',
        value: 'arbeidstilsynet.no',
        defaultChecked: false,
        directPortal: true,
        keywords: ['arbeidsmiljø', 'aml', 'hms', 'verneombud', 'arbeidstilsyn', 'permittering'],
      },
      {
        id: 'nav_rettskilde',
        label: 'NAV Rettskilde / Lovdata NAV',
        desc: 'Rundskriv og instrukser til folketrygdloven og NAV-loven',
        value: 'lovdata.no/nav',
        defaultChecked: false,
        directPortal: true,
        keywords: ['nav', 'folketrygd', 'trygderett', 'stønad', 'arbeidsavklaringspenger', 'dagpenger'],
      },
      {
        id: 'une',
        label: 'UNE (Utlendingsnemnda)',
        desc: 'Praksisnotat og vedtak i utlendingssaker',
        value: 'une.no/praksis',
        defaultChecked: false,
        directPortal: true,
        keywords: ['une', 'utlendingsnemnda', 'asyl', 'visum', 'utvisning', 'statsborgerskap', 'utl'],
      },
      {
        id: 'diskrimineringsnemnda',
        label: 'Diskrimineringsnemnda',
        desc: 'Avgjørelser innen likestilling og diskriminering',
        value: 'diskrimineringsnemnda.no/avgjørelser',
        defaultChecked: false,
        directPortal: true,
        keywords: ['diskriminering', 'likestilling', 'trakassering', 'ldo', 'diskriml'],
      },
      {
        id: 'datatilsynet',
        label: 'Datatilsynet',
        desc: 'GDPR-vedtak, sanksjonssaker og retningslinjer',
        value: 'datatilsynet.no/regelverk-og-verktoy',
        defaultChecked: false,
        directPortal: true,
        keywords: ['gdpr', 'personvern', 'personopplysning', 'datatilsynet', 'personvernforordningen', 'pol'],
      },
      {
        id: 'finanstilsynet',
        label: 'Finanstilsynet',
        desc: 'Rundskriv, tilsynsrapporter og konsesjonsvedtak',
        value: 'finanstilsynet.no/nyheter-og-publikasjoner',
        defaultChecked: false,
        directPortal: true,
        keywords: ['finanstilsyn', 'bank', 'forsikring', 'finans', 'revisjon', 'konsesjon', 'verdipapir'],
      },
      {
        id: 'konkurransetilsynet',
        label: 'Konkurransetilsynet',
        desc: 'Vedtak om fusjoner, kartell og markedsadgang',
        value: 'konkurransetilsynet.no/vedtak-og-uttalelser',
        defaultChecked: false,
        directPortal: true,
        keywords: ['konkurranse', 'fusjon', 'oppkjøp', 'kartell', 'konkurranseloven', 'krrl'],
      },
      {
        id: 'forbrukertilsynet',
        label: 'Forbrukertilsynet',
        desc: 'Vedtak og retningslinjer innen forbrukerrett og markedsføring',
        value: 'forbrukertilsynet.no/vedtak-og-uttalelser',
        defaultChecked: false,
        directPortal: true,
        keywords: ['forbrukertilsyn', 'markedsføringsloven', 'forbruker', 'mfl', 'urimelig avtalevilkår'],
      },
      {
        id: 'forbrukerklageutvalget',
        label: 'Forbrukerklageutvalget',
        desc: 'Vedtak i forbrukerkjøps- og håndverkersaker',
        value: 'forbrukerklageutvalget.no/vedtak',
        defaultChecked: false,
        keywords: ['forbrukerkjøp', 'håndverker', 'reklamasjon', 'mangel kjøp', 'fkjl'],
      },
      {
        id: 'nkom',
        label: 'Nkom (Nasjonal kommunikasjonsmyndighet)',
        desc: 'Vedtak innen elektronisk kommunikasjon og post',
        value: 'nkom.no/vedtak',
        defaultChecked: false,
        directPortal: true,
        keywords: ['nkom', 'elektronisk kommunikasjon', 'ekomloven', 'post', 'telenor', 'tele'],
      },
      {
        id: 'nve',
        label: 'NVE (Norges vassdrags- og energidirektorat)',
        desc: 'Vedtak og konsesjoner innen energi og vassdragsrett',
        value: 'nve.no/juridiske-dokumenter',
        defaultChecked: false,
        directPortal: true,
        keywords: ['nve', 'vassdrag', 'energi', 'konsesjon', 'regulering', 'strøm', 'vannkraft'],
      },
      {
        id: 'patentstyret',
        label: 'Patentstyret',
        desc: 'Vedtak og avgjørelser innen patent, varemerke og design',
        value: 'patentstyret.no',
        defaultChecked: false,
        directPortal: true,
        keywords: ['patent', 'varemerke', 'design', 'immaterialrett', 'ip', 'patentstyret'],
      },
      {
        id: 'statsforvalter',
        label: 'Statsforvalteren',
        desc: 'Statlige tilsyns- og klageinstanser i fylkene',
        value: 'statsforvalteren.no',
        defaultChecked: false,
        directPortal: true,
        keywords: ['statsforvalter', 'fylkesmann', 'klage', 'tilsyn', 'kommunerett klage'],
      },
      {
        id: 'lovdata_rundskriv',
        label: 'Lovdata: Rundskriv',
        desc: 'Departementale og direktoratets rundskriv via Lovdata',
        value: 'lovdata.no/dokument/RUNDSKRIV',
        defaultChecked: false,
        directPortal: true,
        keywords: ['rundskriv', 'instruks', 'tolkningsbrev', 'departementsbrev'],
      },
    ],
  },
  {
    id: 'cat_akademisk',
    title: '5. Akademisk & Juridisk Litteratur',
    colorClass: 'weight-forarbeid',
    weight: 3,
    sources: [
      {
        id: 'juridika',
        label: 'Juridika.no (Universitetsforlaget)',
        desc: 'Kommentarutgaver, lærebøker og juridiske tidsskrifter i fulltekst',
        value: 'juridika.no',
        defaultChecked: false,
        directPortal: true,
        keywords: ['juridika', 'universitetsforlaget', 'kommentarutgave', 'rettsbok', 'juridisk teori'],
        warning: 'Juridika.no krever abonnement for fullteksttilgang. Søk er åpent.',
      },
      {
        id: 'idunn',
        label: 'Idunn.no',
        desc: 'Norsk faglig tidsskriftdatabase – inkl. Lov og Rett, TfE, m.fl.',
        value: 'idunn.no',
        defaultChecked: false,
        directPortal: true,
        keywords: ['idunn', 'lov og rett', 'tidsskrift', 'juridisk artikkel', 'jussens venner', 'njff'],
        warning: 'Idunn.no krever abonnement for fulltekst. Titler og sammendrag er åpne.',
      },
      {
        id: 'uio_jus',
        label: 'UiO Juridisk Fakultet',
        desc: 'Arbeidskopier, PhD-avhandlinger og faglige fremstillinger',
        value: 'uio.no/studier/emner/jus',
        defaultChecked: false,
        keywords: ['uio', 'juridisk fakultet', 'avhandling', 'arbeidsnotat', 'rettsvitenskapelig'],
      },
      {
        id: 'uib_jus',
        label: 'UiB Juridisk Fakultet / BORA',
        desc: 'Forskning og publikasjoner fra juridisk miljø i Bergen (åpen tilgang)',
        value: 'bora.uib.no',
        defaultChecked: false,
        keywords: ['uib', 'bergen', 'bora', 'juridisk', 'åpen tilgang'],
      },
      {
        id: 'cristin',
        label: 'Cristin (NVI-registeret)',
        desc: 'Nasjonalt register over all vitenskapelig publisering i Norge',
        value: 'app.cristin.no',
        defaultChecked: false,
        directPortal: true,
        keywords: ['cristin', 'nvi', 'vitenskapelig', 'forskning', 'publikasjonsliste'],
      },
    ],
  },
  {
    id: 'cat_eu_eos',
    title: '6. EU / EØS-rett',
    colorClass: 'weight-lov',
    weight: 2,
    sources: [
      {
        id: 'eurlex',
        label: 'EUR-Lex',
        desc: 'EUs offisielle rettsportal – forordninger, direktiver og domspraksis',
        value: 'eur-lex.europa.eu',
        defaultChecked: false,
        directPortal: true,
        keywords: ['eu', 'eøs', 'direktiv', 'forordning', 'celex', 'traktat', 'rådsforordning'],
      },
      {
        id: 'curia',
        label: 'Curia (EU-domstolen & Retten)',
        desc: 'Dommer og generaladvokatuttalelser fra EU-domstolen',
        value: 'curia.europa.eu',
        defaultChecked: false,
        directPortal: true,
        keywords: ['eu-domstolen', 'curia', 'generaladvokat', 'prejudisiell', 'tfeu', 'teu'],
      },
      {
        id: 'efta_court',
        label: 'EFTA-domstolen',
        desc: 'Rådgivende uttalelser og dommer om EØS-avtalens innhold',
        value: 'eftacourt.int/cases',
        defaultChecked: false,
        directPortal: true,
        keywords: ['efta', 'eøs-avtalen', 'eea court', 'rådgivende uttalelse', 'esa efta'],
      },
      {
        id: 'esa',
        label: 'ESA (EFTA Surveillance Authority)',
        desc: 'EFTAs overvåkningsorgan – statsstøtte og markedsrett',
        value: 'esa.int/cases',
        defaultChecked: false,
        directPortal: true,
        keywords: ['esa', 'efta surveillance', 'statsstøtte', 'konkurranseregler eøs', 'state aid'],
      },
    ],
  },
  {
    id: 'cat_emr',
    title: '7. Menneskerettigheter',
    colorClass: 'weight-domstol',
    weight: 2,
    sources: [
      {
        id: 'hudoc',
        label: 'HUDOC (EMD – Strasbourg)',
        desc: 'Alle dommer og avvisningsavgjørelser fra Den europeiske menneskerettsdomstol',
        value: 'hudoc.echr.coe.int',
        defaultChecked: false,
        directPortal: true,
        keywords: ['emd', 'emk', 'menneskerettigheter', 'strasbourg', 'hudoc', 'echr', 'emk art'],
      },
      {
        id: 'coe',
        label: 'Europarådet – konvensjoner',
        desc: 'Konvensjoner, traktater og anbefalinger fra Europarådet',
        value: 'coe.int/en/web/conventions',
        defaultChecked: false,
        directPortal: true,
        keywords: ['europarådet', 'council of europe', 'konvensjon', 'emk artikkel', 'cets'],
      },
      {
        id: 'un_treaty',
        label: 'UN Treaty Collection',
        desc: 'FNs traktatregister – internasjonale konvensjoner og protokoller',
        value: 'treaties.un.org',
        defaultChecked: false,
        directPortal: true,
        keywords: ['fn', 'un', 'internasjonale konvensjoner', 'traktat', 'protokoll fn'],
      },
      {
        id: 'ohchr',
        label: 'OHCHR (FN Menneskerettigheter)',
        desc: 'FNs høykommissær – komitéuttalelser, generelle kommentarer og rapporter',
        value: 'ohchr.org',
        defaultChecked: false,
        directPortal: true,
        keywords: ['ohchr', 'fn menneskerettigheter', 'komitéuttalelse', 'sp', 'øsk', 'cedaw', 'crc'],
      },
    ],
  },
  {
    id: 'cat_internasjonal',
    title: '8. Internasjonal & Komparativ Rett',
    colorClass: 'weight-domstol',
    weight: 3,
    sources: [
      {
        id: 'icj',
        label: 'ICJ (Den internasjonale domstol)',
        desc: 'FNs øverste domstol – mellomstatlige tvister og rådgivende uttalelser',
        value: 'icj-cij.org/cases',
        defaultChecked: false,
        directPortal: true,
        keywords: ['icj', 'internasjonal domstol', 'haag', 'mellomstatlig', 'folkerett'],
      },
      {
        id: 'itlos',
        label: 'ITLOS (Havrettsdomstolen)',
        desc: 'Internasjonalt tribunal for havrett i Hamburg',
        value: 'itlos.org/cases',
        defaultChecked: false,
        keywords: ['itlos', 'havrett', 'unclos', 'kontinentalsokkel', 'havretten'],
      },
      {
        id: 'wto_dispute',
        label: 'WTO Tvisteløsning',
        desc: 'WTOs tvisteløsningspanel og ankeorgan',
        value: 'wto.org/english/tratop_e/dispu_e',
        defaultChecked: false,
        directPortal: true,
        keywords: ['wto', 'gatt', 'handelsrett', 'tvisteløsning', 'panel wto'],
      },
      {
        id: 'retsinformation',
        label: 'Retsinformation.dk (Danmark)',
        desc: 'Dansk lovportal – nyttig for komparativ nordisk rett',
        value: 'retsinformation.dk',
        defaultChecked: false,
        directPortal: true,
        keywords: ['dansk', 'nordisk', 'retsinformation', 'komparativ', 'dansk lov'],
      },
      {
        id: 'riksdagen_se',
        label: 'Riksdagen.se (Sverige)',
        desc: 'Svensk lovportal – nyttig for komparativ nordisk rett',
        value: 'riksdagen.se/sv/dokument-och-lagar/lagar',
        defaultChecked: false,
        directPortal: true,
        keywords: ['svensk', 'riksdagen', 'nordisk', 'komparativ', 'svensk lov'],
      },
    ],
  },
];

// =============================================================
// FAGOMRÅDE-BUNDLES
// =============================================================
const BUNDLES = [
  {
    id: 'all', label: '✓ Alle', sourceIds: null,
  },
  {
    id: 'arbeidsrett', label: '👷 Arbeidsrett',
    sourceIds: ['ld_lover','ld_forskrifter','norgeslover','reg_nou','reg_prop','reg_tolkning','ld_hr','ld_lagmannsrett','ld_arbeidsretten','hoyesterett_web','arbeidstilsynet','diskrimineringsnemnda','nav_rettskilde'],
  },
  {
    id: 'forretningsjus', label: '🏢 Forretningsjus & Skatt',
    sourceIds: ['ld_lover','ld_forskrifter','norgeslover','reg_nou','reg_prop','ld_hr','hoyesterett_web','skatteetaten','skatteklagenemnda','finanstilsynet','konkurransetilsynet','eurlex','efta_court'],
  },
  {
    id: 'forvaltning', label: '🏛️ Forvaltningsrett',
    sourceIds: ['ld_lover','ld_forskrifter','norgeslover','reg_nou','reg_prop','reg_tolkning','stortinget_dok','dfo_kudos','lovdata_rundskriv','riksrevisjonen','ld_hr','sivilombudet','datatilsynet','statsforvalter'],
  },
  {
    id: 'strafferett', label: '⚖️ Strafferett',
    sourceIds: ['ld_lover','ld_forskrifter','norgeslover','reg_nou','reg_prop','ld_hr','ld_lagmannsrett','ld_tingrett','hoyesterett_web'],
  },
  {
    id: 'familierett', label: '👨‍👩‍👧 Familie & Arv',
    sourceIds: ['ld_lover','ld_forskrifter','norgeslover','reg_nou','reg_prop','ld_hr','ld_lagmannsrett'],
  },
  {
    id: 'menneskerett', label: '🌍 Menneskerettigheter',
    sourceIds: ['ld_lover','norgeslover','ld_hr','hoyesterett_web','hudoc','coe','un_treaty','ohchr','efta_court','eurlex'],
  },
  {
    id: 'ip', label: '💡 Immaterialrett (IP)',
    sourceIds: ['ld_lover','ld_forskrifter','norgeslover','reg_nou','reg_prop','ld_hr','patentstyret','eurlex','curia'],
  },
  {
    id: 'domstoler', label: '🏛 Kun domstoler',
    sourceIds: ['ld_hr','ld_lagmannsrett','ld_tingrett','hoyesterett_web','rettspraksis_no','ld_arbeidsretten','ld_trygderetten','efta_court','hudoc'],
  },
];

// =============================================================
// JURIDISK TESAURUS / SYNONYMUTVIDELSE
// =============================================================
const JURIDISK_TESAURUS = {
  mislighold: ['kontraktsbrudd', 'avvik', 'kontraktsmislighold', 'vesentlig mislighold', 'misligholdelse'],
  oppsigelse: ['avskjed', 'sluttavtale', 'arbeidsforholdets opphør', 'endringsoppsigelse', 'uppsägning'],
  erstatning: ['skadeserstatning', 'oppreisning', 'ansvar', 'culpaansvar', 'objektivt ansvar', 'menerstatning'],
  mangel: ['feil', 'kjøpsmangel', 'leveringsavvik', 'rettslig mangel', 'faktisk mangel'],
  ekspropriasjon: ['tvangserverv', 'rådighetsinnskrenkning', 'avståelse', 'ekspropriasjon'],
  straff: ['sanksjoner', 'fengselsstraff', 'bøtestraff', 'forvaring', 'samfunnsstraff', 'straffansvar'],
  personvern: ['GDPR', 'personopplysninger', 'behandlingsgrunnlag', 'samtykke', 'personvernforordningen'],
  diskriminering: ['trakassering', 'likestilling', 'usaklig forskjellsbehandling', 'direkte diskriminering', 'indirekte diskriminering'],
  voldgift: ['mekling', 'alternativ tvisteløsning', 'ADR', 'skilsrett', 'voldgiftsklausul'],
  fusjon: ['sammenslåing', 'virksomhetsoverdragelse', 'oppkjøp', 'aksjeoverdragelse', 'foretakssammenslutning'],
  forvaltningsvedtak: ['enkeltvedtak', 'forskriftsvedtak', 'forvaltningsloven', 'klagerett', 'dispensasjon'],
  uaktsomhet: ['culpa', 'forsømmelse', 'uaktsom', 'grov uaktsomhet', 'simpel uaktsomhet'],
};

// Eksporter
window.APP_VERSION = APP_VERSION;
window.SEARCH_ENGINES = SEARCH_ENGINES;
window.PORTAL_SEARCH_URLS = PORTAL_SEARCH_URLS;
window.SOURCE_CATEGORIES = SOURCE_CATEGORIES;
window.BUNDLES = BUNDLES;
window.JURIDISK_TESAURUS = JURIDISK_TESAURUS;
window.LOVNAVN_AUTOCOMPLETE = LOVNAVN_AUTOCOMPLETE;
